# Generated by Django 3.1.3 on 2020-12-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroReceta', '0003_auto_20201202_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='RegistroReceta/img/'),
        ),
    ]
